import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:jni/jni.dart';
import 'package:jni_flutter/jni_flutter.dart';

// ignore: uri_does_not_exist — generated by: dart run tool/jnigen.dart
import 'exoplayer.g.dart';

import 'cache_config.dart';
import 'drm_config.dart';
import 'media_item_builder.dart';
import 'player_state.dart';
import 'track_selector_helper.dart';

export 'player_state.dart';
export 'track_selector_helper.dart';
export 'media_item_builder.dart';
export 'drm_config.dart';
export 'cache_config.dart';

/// High-level Dart controller for an ExoPlayer instance.
///
/// All JNI calls that touch ExoPlayer internals are dispatched to the Android
/// main thread via [_runOnMainThread], which uses [android.os.Handler] with
/// [Looper.getMainLooper()] — both generated by jnigen from tool/jnigen.dart.
///
/// Lifecycle:
/// ```
/// final player = ExoPlayerController();
/// await player.init(cacheConfig: CacheConfig());
/// player.setMediaUrl('https://example.com/stream.m3u8');
/// player.play();
/// ...
/// player.dispose();
/// ```
class ExoPlayerController extends ChangeNotifier {
  ExoPlayer? _player;
  DefaultTrackSelector? _trackSelector;

  // ── Shared-cache singleton ─────────────────────────────────────────────────
  // SimpleCache enforces a single-owner lock per directory. All controllers
  // that use caching share one SimpleCache instance; the last one to dispose
  // releases it.
  static SimpleCache? _sharedCache;
  static int _sharedCacheRefCount = 0;
  bool _ownsSharedCache =
      false; // true when this instance incremented the count

  // ── State streams ──────────────────────────────────────────────────────────
  final _stateController = StreamController<ExoPlayerState>.broadcast();
  final _errorController = StreamController<ExoPlaybackException>.broadcast();
  final _positionController = StreamController<PlayerPosition>.broadcast();

  Stream<ExoPlayerState> get stateStream => _stateController.stream;
  Stream<ExoPlaybackException> get errorStream => _errorController.stream;
  Stream<PlayerPosition> get positionStream => _positionController.stream;

  // ── Observable state ───────────────────────────────────────────────────────
  ExoPlayerState _state = ExoPlayerState.idle;
  bool _isPlaying = false;
  bool _isLoading = true;
  Duration _duration = Duration.zero;
  Duration _position = Duration.zero;
  double _volume = 1.0;
  double _playbackSpeed = 1.0;
  RepeatMode _repeatMode = RepeatMode.off;
  bool _shuffleModeEnabled = false;
  int _videoWidth = 0;
  int _videoHeight = 0;
  int _currentMediaItemIndex = 0;

  ExoPlayerState get state => _state;
  bool get isPlaying => _isPlaying;
  bool get isLoading => _isLoading;
  Duration get duration => _duration;
  Duration get position => _position;
  double get volume => _volume;
  double get playbackSpeed => _playbackSpeed;
  RepeatMode get repeatMode => _repeatMode;
  bool get shuffleModeEnabled => _shuffleModeEnabled;
  int get videoWidth => _videoWidth;
  int get videoHeight => _videoHeight;
  int get currentMediaItemIndex => _currentMediaItemIndex;

  /// Video aspect ratio (width / height). Falls back to 16:9 until the first
  /// frame is decoded and [onVideoSizeChanged] fires.
  double get aspectRatio => (_videoWidth > 0 && _videoHeight > 0)
      ? _videoWidth / _videoHeight
      : 16.0 / 9.0;

  bool get isInitialized => _player != null;

  // ── Position ticker ───────────────────────────────────────────────────────
  Timer? _positionTimer;

  // ── Texture surface ──────────────────────────────────────────────────────
  int? _textureId;

  // Tracks the pool slot we claimed — only cleared in dispose().
  // _textureId may be null'd by detachTexture() (for UI), but the pool
  // slot must be held until dispose() releases it.
  int? _claimedTextureId;

  // Polls consumeSurfaceRefresh() every 300 ms for ~10 s after attachTexture.
  // Catches onSurfaceAvailable fired after app-resume on Impeller/Vulkan.
  Timer? _surfaceRefreshTimer;

  // Guard: prevents a second concurrent attachTexture() while the first
  // _runOnMainThread() call is awaited.
  bool _attachingTexture = false;

  // ── Lifecycle guard ───────────────────────────────────────────────────────
  bool _disposed = false;

  // Set by onPlayerError; consumed in onPlaybackStateChanged (buffering) to
  // re-attach the surface after error recovery.  ExoPlayer drops its surface
  // reference when it enters STATE_IDLE on error.
  bool _hadError = false;

  // ── JNI listener (stored so it can be removed before player release) ──────
  Player$Listener? _listener;

  /// The Flutter texture ID to pass to a [Texture] widget, or null if no
  /// surface has been attached via [attachTexture].
  int? get textureId => _textureId;

  // ── Android main-thread dispatcher ────────────────────────────────────────

  /// Runs [fn] on the Android main thread by posting a [JRunnable] to a
  /// [Handler] backed by [Looper.getMainLooper()].
  ///
  /// This requires the real JNI bindings (generated via
  /// `dart run tool/jnigen.dart`). Both [Looper] and [Handler] are included
  /// in the jnigen class list in `tool/jnigen.dart`.
  // Single Handler per process — avoids creating a new JNI global ref on every call.
  static Handler? _mainHandler;

  static Future<void> _runOnMainThread(void Function() fn) {
    final completer = Completer<void>();
    (_mainHandler ??= Handler.new$2(Looper.mainLooper)).post(
      Runnable.implement(
        $Runnable(
          run: () {
            try {
              fn();
              completer.complete();
            } catch (e, st) {
              completer.completeError(e, st);
            }
          },
        ),
      ),
    );
    return completer.future;
  }

  // ── Init ──────────────────────────────────────────────────────────────────

  /// Initialises ExoPlayer via JNI.
  ///
  /// Must be called before any playback methods.
  /// Optionally pass a [CacheConfig] to enable local media caching and a
  /// [TrackSelectorHelper] to pre-configure track selection.
  ///
  /// Use [minBufferMs] / [maxBufferMs] to reduce heap when running multiple
  /// simultaneous instances (e.g. 2000 / 8000 for a 4-player grid).
  Future<void> init({
    CacheConfig cacheConfig = CacheConfig.none,
    TrackSelectorHelper? trackSelectorHelper,
    int minBufferMs = 15000,
    int maxBufferMs = 50000,
    int bufferForPlaybackMs = 1500,
    int bufferForPlaybackAfterRebufferMs = 5000,
  }) async {
    if (_player != null) return;

    await _runOnMainThread(() {
      final context = androidApplicationContext.as(Context.type);

      // ── Track selector ───────────────────────────────────────────────────
      _trackSelector = DefaultTrackSelector(context);

      // ── Load control ─────────────────────────────────────────────────────
      final loadControl = DefaultLoadControl$Builder()
          .setBufferDurationsMs(
            minBufferMs,
            maxBufferMs,
            bufferForPlaybackMs,
            bufferForPlaybackAfterRebufferMs,
          )
          ?.build();

      // ── Cache (singleton per process) ──────────────────────────────────────
      // SimpleCache locks its directory — only one instance may exist at a time.
      // We maintain a static singleton + ref-count so all controllers share it.
      if (cacheConfig.maxBytes > 0) {
        if (_sharedCache == null) {
          final cacheDir = cacheConfig.cacheDirectory != null
              ? File(cacheConfig.cacheDirectory!.path.toJString())
              : File(
                  ('${context.cacheDir?.absolutePath?.toDartString() ?? '/cache'}/exoplayer_cache')
                      .toJString(),
                );
          final evictor = LeastRecentlyUsedCacheEvictor(
            cacheConfig.maxBytes,
          );
          // Wrap in try-catch: after a hot restart the Dart statics reset to
          // null but the Android JVM still holds the old SimpleCache lock on
          // the directory.  If creation fails (stale lock), we proceed without
          // caching rather than crashing the init.
          try {
            _sharedCache = SimpleCache(cacheDir, evictor);
          } catch (_) {
            // Stale lock from a previous Dart VM lifetime (hot restart).
            // Cache will be unavailable for this session; playback still works.
          }
        }
        if (_sharedCache != null) {
          _sharedCacheRefCount++;
          _ownsSharedCache = true;
        }
      }

      // ── Build ExoPlayer ──────────────────────────────────────────────────
      // setLooper pins ExoPlayer to the Android main looper so all internal
      // state machine transitions happen on the correct thread.
      _player = ExoPlayer$Builder(context)
          .setTrackSelector(_trackSelector!)
          ?.setLoadControl(loadControl)
          ?.setLooper(Looper.mainLooper)
          ?.build();

      // ── Attach listener ───────────────────────────────────────────────────
      _listener = _buildListener();
      _player!.addListener(_listener!);
    });

    // Apply track selector parameters if provided
    if (trackSelectorHelper != null && _trackSelector != null) {
      await _runOnMainThread(() {
        trackSelectorHelper.apply(_trackSelector!);
      });
    }

    // Start position polling at 500 ms intervals
    _positionTimer = Timer.periodic(const Duration(milliseconds: 500), (_) {
      _pollPosition();
    });

    notifyListeners();
  }

  // ── Media loading ─────────────────────────────────────────────────────────

  /// Sets a single media URL. Supports HLS (.m3u8), DASH (.mpd), and
  /// progressive streams automatically via ExoPlayer's default media source.
  void setMediaUrl(String url, {DrmConfig? drm}) {
    _assertInitialized();
    final item = MediaItemBuilder()
        .setUri(url)
        .let((b) => drm != null ? b.setDrmConfig(drm) : b)
        .build();
    _runOnMainThread(() {
      _player!.setMediaItem(item);
      _player!.prepare$2();
    });
  }

  /// Sets a pre-built [MediaItem] (use [MediaItemBuilder] for full control).
  void setMediaItem(MediaItem item) {
    _assertInitialized();
    _runOnMainThread(() {
      _player!.setMediaItem(item);
      _player!.prepare$2();
    });
  }

  /// Sets a playlist of [MediaItem]s.
  void setPlaylist(List<MediaItem> items) {
    _assertInitialized();
    _runOnMainThread(() {
      final jList = JArrayList<MediaItem>();
      try {
        for (final item in items) {
          jList.add(item);
        }
        _player!.setMediaItems(jList);
        _player!.prepare$2();
      } finally {
        jList.release(); // release JNI local ref after hand-off to ExoPlayer
      }
    });
  }

  /// Adds a [MediaItem] to the end of the current playlist.
  void addMediaItem(MediaItem item) {
    _assertInitialized();
    _runOnMainThread(() => _player!.addMediaItem(item));
  }

  /// Removes the media item at [index] from the playlist.
  void removeMediaItem(int index) {
    _assertInitialized();
    _runOnMainThread(() => _player!.removeMediaItem(index));
  }

  // ── Playback controls ─────────────────────────────────────────────────────

  void play() {
    _assertInitialized();
    _runOnMainThread(() => _player!.play());
  }

  void pause() {
    _assertInitialized();
    _runOnMainThread(() => _player!.pause());
  }

  void stop() {
    _assertInitialized();
    _runOnMainThread(() => _player!.stop());
  }

  void seekTo(Duration position) {
    _assertInitialized();
    _runOnMainThread(() => _player!.seekTo(position.inMilliseconds));
  }

  /// Seek to [position] in media item at [mediaItemIndex].
  void seekToMediaItem(int mediaItemIndex, Duration position) {
    _assertInitialized();
    _runOnMainThread(
      () => _player!.seekTo$1(mediaItemIndex, position.inMilliseconds),
    );
  }

  void seekToNext() {
    _assertInitialized();
    _runOnMainThread(() => _player!.seekToNext());
  }

  void seekToPrevious() {
    _assertInitialized();
    _runOnMainThread(() => _player!.seekToPrevious());
  }

  void seekToNextMediaItem() {
    _assertInitialized();
    _runOnMainThread(() => _player!.seekToNextMediaItem());
  }

  void seekToPreviousMediaItem() {
    _assertInitialized();
    _runOnMainThread(() => _player!.seekToPreviousMediaItem());
  }

  // ── Volume / speed ────────────────────────────────────────────────────────

  /// Sets playback volume in the range [0.0, 1.0].
  void setVolume(double volume) {
    _assertInitialized();
    _volume = volume.clamp(0.0, 1.0);
    _runOnMainThread(() => _player!.setVolume(_volume));
    notifyListeners();
  }

  /// Sets playback speed. 1.0 is normal speed.
  void setPlaybackSpeed(double speed) {
    if (speed <= 0) {
      throw ArgumentError.value(speed, 'speed', 'Playback speed must be > 0');
    }
    _assertInitialized();
    _playbackSpeed = speed;
    _runOnMainThread(() {
      _player!.setPlaybackParameters(
        PlaybackParameters(speed),
      );
    });
    notifyListeners();
  }

  // ── Repeat / shuffle ──────────────────────────────────────────────────────

  void setRepeatMode(RepeatMode mode) {
    _assertInitialized();
    _repeatMode = mode;
    final jMode = switch (mode) {
      RepeatMode.off => 0,
      RepeatMode.one => 1,
      RepeatMode.all => 2,
    };
    _runOnMainThread(() => _player!.setRepeatMode(jMode));
    notifyListeners();
  }

  void setShuffleModeEnabled(bool enabled) {
    _assertInitialized();
    _shuffleModeEnabled = enabled;
    _runOnMainThread(
      () => _player!.setShuffleModeEnabled(enabled),
    );
    notifyListeners();
  }

  // ── Track selection ───────────────────────────────────────────────────────

  /// Re-configures track selection at runtime.
  void applyTrackSelector(TrackSelectorHelper helper) {
    _assertInitialized();
    _runOnMainThread(() => helper.apply(_trackSelector!));
  }

  // ── Surface / Texture ─────────────────────────────────────────────────────

  // JNI class/method IDs cached lazily (allocated once per process).
  static JClass? _bridgeClass;
  static JStaticMethodId? _createAndClaimTextureMethod;
  static JStaticMethodId? _disposeTextureMethod;
  static JStaticMethodId? _getSurfaceMethod;
  static JStaticMethodId? _consumeSurfaceRefreshMethod;

  static void _initBridgeIds() {
    if (_bridgeClass != null) return;
    _bridgeClass =
        JClass.forName('com/example/exoplayer_jni/ExoPlayerSurfaceBridge');
    // createAndClaimTexture(): creates a fresh SurfaceProducer on the main
    // thread and returns its texture ID.  Must be called via _runOnMainThread.
    _createAndClaimTextureMethod =
        _bridgeClass!.staticMethodId('createAndClaimTexture', '()J');
    // disposeTexture(long): releases the SurfaceProducer.  Should be called
    // after ExoPlayer.release(), inside _runOnMainThread.
    _disposeTextureMethod =
        _bridgeClass!.staticMethodId('disposeTexture', '(J)J');
    _getSurfaceMethod =
        _bridgeClass!.staticMethodId('getSurface', '(J)Landroid/view/Surface;');
    _consumeSurfaceRefreshMethod =
        _bridgeClass!.staticMethodId('consumeSurfaceRefresh', '(J)Z');
  }

  /// Creates a per-player [SurfaceProducer] via JNI and hands its [Surface]
  /// to ExoPlayer — all on the Android main thread so that the
  /// [android.media.ImageReader] listener handler has a valid [Looper].
  ///
  /// Returns the [textureId] to pass to a [Texture] widget.
  /// Idempotent — calling again returns the existing [textureId].
  Future<int> attachTexture() async {
    if (_textureId != null) return _textureId!;
    // Prevent a second concurrent call while _runOnMainThread is awaited.
    if (_attachingTexture) return -1;
    _assertInitialized();
    _initBridgeIds();

    // Re-use a previously claimed producer if detachTexture() was called but
    // dispose() hasn't run yet (Flutter disposes child States before parents).
    if (_claimedTextureId != null) {
      _textureId = _claimedTextureId!;
      // Re-attach to the existing SurfaceProducer surface on the main thread.
      await _runOnMainThread(() {
        try {
          final s = _getSurfaceMethod!.call<Surface, Surface>(
              _bridgeClass!, Surface.type, [_textureId!]);
          _player?.setVideoSurface(s);
          s.release();
        } on JNullError {
          // Surface temporarily gone; onSurfaceAvailable will trigger re-attach.
        }
      });
      if (!_disposed) notifyListeners();
      return _textureId!;
    }

    _attachingTexture = true;

    // Create a fresh SurfaceProducer on the Android main thread, then get
    // the initial Surface and hand it to ExoPlayer — all in one main-thread
    // trip.  Bundling these together ensures:
    //   1. createSurfaceProducer() runs on the main thread (required).
    //   2. The ImageReader.setOnImageAvailableListener Handler is bound to
    //      the main-thread Looper (required — avoids the Looper crash that
    //      affected the last pre-allocated pool slot on Impeller/Vulkan).
    //   3. setVideoSurface() runs on the ExoPlayer looper (main thread).
    int textureId = -1;
    await _runOnMainThread(() {
      textureId = _createAndClaimTextureMethod!
          .call<jlong, int>(_bridgeClass!, jlong.type, []);
      if (textureId < 0) return; // registry not yet available
      try {
        final s = _getSurfaceMethod!
            .call<Surface, Surface>(_bridgeClass!, Surface.type, [textureId]);
        _player?.setVideoSurface(s);
        s.release();
      } on JNullError {
        // Surface unexpectedly null; disposeTexture and retry below.
        _disposeTextureMethod!
            .call<jlong, int>(_bridgeClass!, jlong.type, [textureId]);
        textureId = -1;
      }
    });

    _attachingTexture = false;

    if (_disposed) return -1;

    if (textureId < 0) {
      // Registry not ready yet; retry after a short delay.
      Future.delayed(const Duration(milliseconds: 100), () {
        if (!_disposed && _textureId == null) attachTexture();
      });
      return -1;
    }

    _textureId = textureId;
    _claimedTextureId = textureId;

    // Poll consumeSurfaceRefresh for ~10 s to catch onSurfaceAvailable fired
    // after app-resume (Impeller/Vulkan destroys and recreates the surface
    // when the app is backgrounded).
    _surfaceRefreshTimer?.cancel();
    var pollCount = 0;
    _surfaceRefreshTimer =
        Timer.periodic(const Duration(milliseconds: 300), (t) {
      pollCount++;
      if (_disposed || _textureId == null || pollCount > 33) {
        t.cancel();
        _surfaceRefreshTimer = null;
        return;
      }
      _checkAndReattachIfNeeded();
    });

    if (!_disposed) notifyListeners();
    return textureId;
  }

  /// If the SurfaceProducer for our slot fired onSurfaceCreated while the slot
  /// was claimed, re-fetches and re-sets the surface so ExoPlayer renders to the
  /// new, valid surface instead of the stale placeholder.
  Future<void> _checkAndReattachIfNeeded() async {
    if (_disposed || _textureId == null) return;
    _initBridgeIds();
    final refreshed = _consumeSurfaceRefreshMethod!
        .call<jboolean, bool>(_bridgeClass!, jboolean.type, [_textureId!]);
    if (refreshed) await reattachSurface();
  }

  /// Detaches the surface from ExoPlayer. The [TextureRegistry] entry is kept
  /// alive by the Kotlin plugin for the lifetime of the Flutter engine — no
  /// release channel call needed.
  Future<void> detachTexture() async {
    if (_disposed || _textureId == null) return;
    // Stop polling for surface refreshes — no surface is attached anymore.
    _surfaceRefreshTimer?.cancel();
    _surfaceRefreshTimer = null;
    _textureId = null;
    _runOnMainThread(() => _player?.clearVideoSurface());
    notifyListeners();
  }

  /// Re-attaches the surface after it was recreated by [SurfaceProducer]
  /// (e.g. app returning from background under Impeller/Vulkan).
  ///
  /// Call this from an [AppLifecycleListener.onResume] callback:
  /// ```dart
  /// AppLifecycleListener(onResume: () => controller.reattachSurface());
  /// ```
  Future<void> reattachSurface() async {
    if (_disposed || _textureId == null) return;
    _initBridgeIds();
    // getSurface() delegates to SurfaceProducer.getSurface() which may create
    // a new ImageReader (Handler) — must run on the main thread.
    await _runOnMainThread(() {
      try {
        final s = _getSurfaceMethod!
            .call<Surface, Surface>(_bridgeClass!, Surface.type, [_textureId!]);
        _player?.setVideoSurface(s);
        s.release();
      } on JNullError {
        // Surface temporarily gone; onSurfaceAvailable will re-flag it.
      }
    });
  }

  /// Attaches the player to an already-created [Surface] JNI object directly.
  void setSurface(Surface surface) {
    _assertInitialized();
    _runOnMainThread(() => _player!.setVideoSurface(surface));
  }

  void clearVideoSurface() {
    _assertInitialized();
    _runOnMainThread(() => _player!.clearVideoSurface());
  }

  // ── Raw JNI access ────────────────────────────────────────────────────────

  /// Returns the underlying JNI [ExoPlayer] for advanced use cases.
  ///
  /// Use with caution — calling JNI methods off the main thread will crash.
  ExoPlayer get rawPlayer {
    _assertInitialized();
    return _player!;
  }

  /// Returns the [DefaultTrackSelector] for direct parameter manipulation.
  DefaultTrackSelector get rawTrackSelector {
    _assertInitialized();
    return _trackSelector!;
  }

  // ── Player.Listener (JNI callback) ───────────────────────────────────────

  /// Creates a JNI [Player_Listener] implementation that forwards events
  /// to Dart streams. Uses JNIgen's JImplementer to implement the interface.
  Player$Listener _buildListener() {
    // JNIgen ≥ 0.14 generates JImplementer support for interfaces.
    // The generated glue calls back into Dart via JNI portals.
    return Player$Listener.implement(
      $Player$Listener(
        onEvents: (player, events) {},
        onTimelineChanged: (timeline, i) {},
        onMediaItemTransition: (MediaItem? item, int reason) {
          if (_disposed) return;
          // Update current index from the player
          _currentMediaItemIndex =
              _player?.getCurrentMediaItemIndex() ?? _currentMediaItemIndex;
          // Reset duration on track change
          _duration = Duration.zero;
          _position = Duration.zero;
          notifyListeners();
        },
        onTracksChanged: (tracks) {},
        onMediaMetadataChanged: (metadata) {},
        onPlaylistMetadataChanged: (metadata) {},
        onIsLoadingChanged: (bool loading) {},
        onLoadingChanged: (bool loading) {},
        onAvailableCommandsChanged: (commands) {},
        onTrackSelectionParametersChanged: (params) {},
        onPlayerStateChanged: (bool playWhenReady, int state) {},
        onPlaybackStateChanged: (int state) {
          if (_disposed) return;
          final s = exoPlayerStateFromInt(state);
          _state = s;
          _isLoading = s == ExoPlayerState.buffering;
          _stateController.add(s);
          if (s == ExoPlayerState.buffering && _hadError) {
            // After an error, ExoPlayer drops its surface reference when it
            // enters STATE_IDLE.  Re-attach as soon as it starts buffering the
            // recovery URL so video renders correctly.
            _hadError = false;
            reattachSurface();
          }
          // If onSurfaceCreated fired a new surface while we were buffering,
          // re-attach so ExoPlayer renders to the current live surface.
          _checkAndReattachIfNeeded();
          notifyListeners();
        },
        onPlayWhenReadyChanged: (bool z, int i) {},
        onPlaybackSuppressionReasonChanged: (int i) {},
        onIsPlayingChanged: (bool playing) {
          if (_disposed) return;
          _isPlaying = playing;
          _checkAndReattachIfNeeded();
          notifyListeners();
        },
        onRepeatModeChanged: (int mode) {
          if (_disposed) return;
          _repeatMode = switch (mode) {
            1 => RepeatMode.one,
            2 => RepeatMode.all,
            _ => RepeatMode.off,
          };
          notifyListeners();
        },
        onShuffleModeEnabledChanged: (bool enabled) {
          if (_disposed) return;
          _shuffleModeEnabled = enabled;
          notifyListeners();
        },
        onPlayerError: (PlaybackException? error) {
          if (_disposed || error == null) return;
          _hadError = true;
          final ex = ExoPlaybackException(
            errorCode: error.errorCode,
            message: error.errorCodeName?.toDartString() ??
                'Error ${error.errorCode}',
          );
          _errorController.add(ex);
          // In playlist mode, auto-skip the failed item and continue playback.
          // ExoPlayer enters STATE_IDLE on error and stops — we must manually
          // advance, re-prepare, and resume.
          if ((_player?.getMediaItemCount() ?? 0) > 1 &&
              (_player?.hasNextMediaItem() ?? false)) {
            _runOnMainThread(() {
              if (_disposed || _player == null) return;
              _player!.seekToNextMediaItem();
              _player!.prepare$2();
              _player!.play();
            });
          }
        },
        onPlayerErrorChanged: (PlaybackException? error) {},
        onPositionDiscontinuity: (int i) {},
        onPositionDiscontinuity$1: (pos1, pos2, reason) {},
        onPlaybackParametersChanged: (PlaybackParameters? params) {
          if (_disposed || params == null) return;
          _playbackSpeed = params.speed;
          notifyListeners();
        },
        onSeekBackIncrementChanged: (int j) {},
        onSeekForwardIncrementChanged: (int j) {},
        onMaxSeekToPreviousPositionChanged: (int j) {},
        onAudioSessionIdChanged: (int i) {},
        onAudioAttributesChanged: (attrs) {},
        onVolumeChanged: (double vol) {
          if (_disposed) return;
          _volume = vol;
          notifyListeners();
        },
        onSkipSilenceEnabledChanged: (bool z) {},
        onDeviceInfoChanged: (info) {},
        onDeviceVolumeChanged: (int i, bool z) {},
        onVideoSizeChanged: (VideoSize? size) {
          if (_disposed || size == null) return;
          _videoWidth = size.width;
          _videoHeight = size.height;
          notifyListeners();
        },
        onSurfaceSizeChanged: (int i, int i1) {},
        onRenderedFirstFrame: () {},
        onCues: (list) {},
        onCues$1: (cueGroup) {},
        onMetadata: (metadata) {},
      ),
    );
  }

  // ── Position polling ──────────────────────────────────────────────────────

  void _pollPosition() {
    if (_disposed || _player == null) return;
    _runOnMainThread(() {
      if (_disposed) return; // double-check inside the async callback
      final pos = Duration(milliseconds: _player!.getCurrentPosition());
      final buf = Duration(milliseconds: _player!.getBufferedPosition());
      final dur = Duration(milliseconds: _player!.getDuration());
      _position = pos;
      _duration = dur == const Duration(milliseconds: -9223372036854775808)
          ? Duration.zero
          : dur; // TIME_UNSET sentinel
      _positionController.add(
        PlayerPosition(position: pos, buffered: buf, duration: _duration),
      );
    });
  }

  // ── Dispose ───────────────────────────────────────────────────────────────

  @override
  void dispose() {
    _disposed = true; // must be first — guards all async callbacks
    _positionTimer?.cancel();
    _surfaceRefreshTimer?.cancel();
    _surfaceRefreshTimer = null;
    // Capture IDs/refs before clearing them.
    final releasingId = _claimedTextureId;
    _textureId = null;
    _claimedTextureId = null;
    final listener = _listener;
    _listener = null;
    // Ensure bridge IDs are initialised before entering the main-thread lambda
    // so we can call disposeTexture() there.
    if (releasingId != null) _initBridgeIds();
    _runOnMainThread(() {
      // Stop immediately so audio ceases before release() tears down buffers.
      // Must run on the main thread — ExoPlayer was built with setLooper(mainLooper).
      _player?.stop();
      // Remove listener so ExoPlayer.release() doesn't fire callbacks
      // into Dart after the streams are closed.
      if (listener != null) _player?.removeListener(listener);
      _player?.clearVideoSurface();
      _player?.release();
      // Release the shared cache only when the last user disposes.
      if (_ownsSharedCache) {
        _sharedCacheRefCount--;
        if (_sharedCacheRefCount <= 0) {
          _sharedCache?.release();
          _sharedCache = null;
          _sharedCacheRefCount = 0;
        }
        _ownsSharedCache = false;
      }
      _player = null;
      _trackSelector = null;
      // Release the SurfaceProducer AFTER ExoPlayer is fully torn down so it
      // has already detached from the surface before we free it.
      if (releasingId != null) {
        _disposeTextureMethod!
            .call<jlong, int>(_bridgeClass!, jlong.type, [releasingId]);
      }
    });
    _stateController.close();
    _errorController.close();
    _positionController.close();
    super.dispose();
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  void _assertInitialized() {
    if (_player == null) {
      throw StateError(
        'ExoPlayerController not initialized. Call init() first.',
      );
    }
  }
}

extension _Let<T> on T {
  R let<R>(R Function(T) block) => block(this);
}
